name: Lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review, edited]
  workflow_dispatch:

jobs:
    markdownlint:
        runs-on: ubuntu-latest
    
        steps:
          - uses: actions/checkout@v4
    
          - name: Run markdownlint
            run: |
              sudo npm install -g markdownlint-cli
              markdownlint $(find . -name '*.md' | grep -vF './.git')
    
    codespell:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - uses: codespell-project/actions-codespell@v2
          with:
            exclude_file: *.svg
