name: Generate Profile Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Base Options
          user: kbdharun
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          config_timezone: Asia/Calcutta
          config_display: large

          # Plugin Options
          plugin_discussions: yes
          plugin_discussions_categories: yes

          plugin_gists: yes

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 10
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base

          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit

          plugin_sponsorships: yes
          plugin_sponsorships_sections: amount, sponsorships
          plugin_sponsorships_size: 24

          plugin_topics: yes
          plugin_topics_limit: 30
          plugin_topics_mode: icons
          plugin_topics_sort: stars

          plugin_traffic: yes
